from enum import Enum


class ErrorCode(str, Enum):
    # Auth errors  1xxx
    OTP_RATE_LIMITED = "AUTH_1001"
    OTP_INVALID = "AUTH_1002"
    OTP_EXPIRED = "AUTH_1003"
    OTP_MAX_ATTEMPTS = "AUTH_1004"
    OTP_SEND_FAILED = "AUTH_1005"
    JWT_INVALID = "AUTH_1006"
    JWT_EXPIRED = "AUTH_1007"
    NOT_REGISTERED = "AUTH_1008"
    USER_INACTIVE = "AUTH_1009"

    # Registration errors  2xxx
    FACE_ALREADY_REGISTERED = "REG_2001"
    FACE_NOT_DETECTED = "REG_2002"
    FACE_VIDEO_TOO_LARGE = "REG_2003"
    FACE_VIDEO_INVALID_FORMAT = "REG_2004"
    FACE_EMBEDDING_FAILED = "REG_2005"
    FACE_DUPLICATE_HASH = "REG_2006"
    FACE_DUPLICATE_EMBEDDING = "REG_2007"
    AADHAAR_INVALID_FORMAT = "REG_2008"
    AADHAAR_ALREADY_REGISTERED = "REG_2009"
    AADHAAR_API_FAILED = "REG_2010"
    AADHAAR_VERIFICATION_FAILED = "REG_2011"
    FACE_NOT_YET_REGISTERED = "REG_2012"

    # Skill / application errors  3xxx
    SKILL_NOT_FOUND = "SKILL_3001"
    MAX_ATTEMPTS_REACHED = "SKILL_3002"
    IN_COOLDOWN = "SKILL_3003"
    APPLICATION_NOT_FOUND = "SKILL_3004"

    # Document errors  4xxx
    UPLOAD_NOT_FOUND = "DOC_4001"
    UPLOAD_ALREADY_COMPLETE = "DOC_4002"
    CHUNK_DUPLICATE = "DOC_4003"
    CHUNKS_MISSING = "DOC_4004"
    FILE_TOO_LARGE = "DOC_4005"
    INVALID_FILE_FORMAT = "DOC_4006"
    DEGREE_CHECK_FAILED = "DOC_4007"

    # Interview errors  5xxx
    SESSION_NOT_FOUND = "INTERVIEW_5001"
    SESSION_ALREADY_ENDED = "INTERVIEW_5002"
    SESSION_NOT_ACTIVE = "INTERVIEW_5003"
    NO_ACTIVE_APPLICATION = "INTERVIEW_5004"

    # Kafka errors  6xxx
    KAFKA_SEND_FAILED = "KAFKA_6001"
    KAFKA_NOT_CONNECTED = "KAFKA_6002"

    # ML service errors  7xxx
    ML_SERVICE_UNREACHABLE = "ML_7001"
    ML_FACE_CHECK_FAILED = "ML_7002"
    ML_DEGREE_CHECK_FAILED = "ML_7003"
    ML_VERDICT_NOT_FOUND = "ML_7004"

    # DB errors  8xxx
    DB_CONNECTION_FAILED = "DB_8001"
    DB_QUERY_FAILED = "DB_8002"
    DB_INTEGRITY_ERROR = "DB_8003"

    # Cache errors  9xxx
    REDIS_CONNECTION_FAILED = "CACHE_9001"
    REDIS_OPERATION_FAILED = "CACHE_9002"

    # Generic  0xxx
    INTERNAL_ERROR = "SRV_0001"
    VALIDATION_ERROR = "SRV_0002"
    NOT_FOUND = "SRV_0003"
    FORBIDDEN = "SRV_0004"
